name: 'Terrafrm Validate'
description: 'This action uses the `terraform validate` command to check that a terraform configuration is valid. This can be used to check that a configuration is valid before creating a plan.'
author: 'Benoit Blais'

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    type: string
  workspace:
    description: Name of the workspace to use for the `terraform.workspace` value while validating.
    required: false
    default: 'default'
    type: string

runs:
  using: "composite"
  steps:
    - id: BashScript
      shell: bash
      run: bash ${{ github.action_path }}/main.sh
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_WORKSPACE: ${{ inputs.workspace }}
